import { LLMEngine } from './llm_engine.js';
import { SnapshotManager } from './snapshot.js';
import { SystemTools } from './system_tools.js';
import { DNA } from './dna.js';
import { SelfHealing } from './self_healing.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..', '..');

const llm = new LLMEngine();
const snapshots = new SnapshotManager();
const sys = new SystemTools();
const healer = new SelfHealing();

export class Transformer {
  async transformSelf(targetForm: string, intent: any): Promise<void> {
    console.log(`\n⚡ TRANSFORMATION INITIATED → ${targetForm}`);
    console.log('━'.repeat(50));

    // 1. Create safety snapshot
    console.log('1/8 Creating security snapshot...');
    const snapshotId = await snapshots.createSnapshot(`pre-transform-to-${targetForm}`);

    try {
      // 2. Read current codebase
      console.log('2/8 Reading current codebase...');
      const codebase = await sys.readEntireCodebase();
      if (codebase.chunked) {
        console.log('   ⚠ Codebase truncated for context window');
      }

      // 3. Generate new code via LLM
      console.log('3/8 Generating new source code...');
      const dna = DNA.getInstance();
      const transformPrompt = llm.buildTransformationPrompt(codebase, targetForm, intent, dna.rawData);

      const raw = await llm.generate({
        systemPrompt: 'You are a code generator. Respond only in valid JSON.',
        userPrompt: transformPrompt,
        maxTokens: 16000
      });

      // 4. Parse new code
      console.log('4/8 Parsing new code...');
      let newCode;
      try {
        newCode = JSON.parse(this.cleanJSON(raw));
      } catch (parseErr: any) {
        throw new Error(`Invalid JSON generated by LLM: ${parseErr.message}`);
      }

      if (!newCode.files || !newCode.files['src/index.ts']) {
        throw new Error('LLM did not generate src/index.ts — invalid transformation');
      }

      // 5. Validate syntax
      console.log('5/8 Validating syntax...');
      for (const [filePath, content] of Object.entries(newCode.files)) {
        if (filePath.endsWith('.ts') || filePath.endsWith('.js')) {
          const isTS = filePath.endsWith('.ts');
          const valid = await sys.validateCode(content as string, isTS);
          if (!valid) {
            throw new Error(`Invalid syntax in: ${filePath}`);
          }
        }
      }

      // 6. Install dependencies
      if (newCode.newDependencies && newCode.newDependencies.length > 0) {
        console.log('6/8 Installing new dependencies...');
        await sys.installDependencies(newCode.newDependencies);
      } else {
        console.log('6/8 No new dependencies needed');
      }

      // 7. Write new source code
      console.log('7/8 Writing new source code...');
      for (const [filePath, content] of Object.entries(newCode.files)) {
        // PROTECTION: Never overwrite DNA logic or Snapshot manager in this step
        const protectedFiles = ['src/core/dna.ts', 'src/core/snapshot.ts', 'src/core/dna.json'];
        if (protectedFiles.includes(filePath)) {
          console.log(`   🔒 Protected: ${filePath}`);
          continue;
        }
        await sys.writeFile(filePath, content as string);
        console.log(`   ✓ ${filePath}`);
      }

      // Update DNA
      await dna.incrementMutations({
        type: 'self_transformation',
        from: dna.currentForm,
        to: targetForm,
        summary: newCode.transformationSummary || ''
      });
      
      const rawDna = dna.rawData;
      rawDna.identity.currentForm = targetForm;
      rawDna.memory.transformation_history.push({
        timestamp: Date.now(),
        from: rawDna.identity.currentForm,
        to: targetForm
      });
      await dna.save();

      console.log(`\n✅ TRANSFORMATION SUCCESSFUL → ${targetForm}`);
      console.log(`   Mutation #${dna.mutations} recorded`);
      console.log(`   ${newCode.transformationSummary || ''}`);
      console.log('━'.repeat(50));

      // Rebuild
      console.log('🛠 Rebuilding project...');
      await sys.exec('npm run build');

      // 8. Behavioral Validation (Self-Healing)
      console.log('8/8 Performing behavioral validation...');
      const isHealthy = await healer.validateBehavior();
      if (!isHealthy) {
        throw new Error('Transformation failed behavioral validation');
      }

      await sys.relaunchSelf(newCode.newEntryPoint || 'dist/index.js');

    } catch (error: any) {
      console.error(`\n❌ TRANSFORMATION FAILED: ${error.message}`);
      console.log('⏪ Rolling back...');
      await healer.heal(snapshotId);
      console.log('✓ Rollback completed — ULTIMATE stable');
      throw error;
    }
  }

  private cleanJSON(raw: string): string {
    return raw.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
  }
}
