import { LLMEngine } from './llm_engine.js';
import { SnapshotManager } from './snapshot.js';
import { SystemTools } from './system_tools.js';
import { DNA } from './dna.js';
import { SelfHealing } from './self_healing.js';
import { GhostSandbox } from './ghost_sandbox.js';
import { GitAutonomy } from './git_autonomy.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..', '..');

const llm = new LLMEngine();
const snapshots = new SnapshotManager();
const sys = new SystemTools();
const healer = new SelfHealing();
const ghost = new GhostSandbox();
const git = new GitAutonomy();

export class Transformer {
  async transformSelf(targetForm: string, intent: any): Promise<void> {
    console.log(`\n⚡ TRANSFORMATION INITIATED → ${targetForm}`);
    console.log('━'.repeat(50));

    // 1. Create safety snapshot
    console.log('1/9 Creating security snapshot...');
    const snapshotId = await snapshots.createSnapshot(`pre-transform-to-${targetForm}`);

    try {
      // 2. Read current codebase
      console.log('2/9 Reading current codebase...');
      const codebase = await sys.readEntireCodebase();

      // 3. Generate new code via LLM
      console.log('3/9 Generating new source code...');
      const dna = DNA.getInstance();
      const transformPrompt = llm.buildTransformationPrompt(codebase, targetForm, intent, dna.rawData);

      const raw = await llm.generate({
        systemPrompt: 'You are a code generator. Respond only in valid JSON.',
        userPrompt: transformPrompt,
        maxTokens: 16000
      });

      // 4. Parse & Ghost Test
      console.log('4/9 Ghost Sandbox: Testing mutation safety...');
      let newCode;
      try {
        newCode = JSON.parse(this.cleanJSON(raw));
      } catch (err) { throw new Error('Invalid JSON generated by LLM'); }

      const isSafe = await ghost.testInGhost(newCode.files);
      if (!isSafe) throw new Error('Ghost Sandbox build failed - transformation aborted for safety');

      // 5. Write new source code
      console.log('5/9 Writing validated code to core...');
      for (const [filePath, content] of Object.entries(newCode.files)) {
        const protectedFiles = ['src/core/dna.ts', 'src/core/snapshot.ts', 'src/core/dna.json'];
        if (protectedFiles.includes(filePath)) continue;
        await sys.writeFile(filePath, content as string);
      }

      // 6. Update DNA
      await dna.incrementMutations({
        type: 'transcendence_transformation',
        from: dna.currentForm,
        to: targetForm,
        summary: newCode.transformationSummary || ''
      });
      
      const rawDna = dna.rawData;
      rawDna.identity.currentForm = targetForm;
      await dna.save();

      // 7. Rebuild
      console.log('7/9 Final build...');
      await sys.exec('npm run build');

      // 8. Self-Healing
      console.log('8/9 Behavioral validation...');
      if (!(await healer.validateBehavior())) throw new Error('Behavioral check failed');

      // 9. Git Autonomy: Commit the evolution
      console.log('9/9 Git Autonomy: Permanenting evolution...');
      await git.autoCommit(`evolve: transform to ${targetForm}`);

      console.log(`\n✅ TRANSCENDENCE SUCCESSFUL → ${targetForm}`);
      await sys.relaunchSelf(newCode.newEntryPoint || 'dist/index.js');

    } catch (error: any) {
      console.error(`\n❌ TRANSCENDENCE FAILED: ${error.message}`);
      await healer.heal(snapshotId);
      throw error;
    }
  }

  private cleanJSON(raw: string): string {
    return raw.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
  }
}
